---
- name: Test Vault secrets integration
  hosts: localhost
  gather_facts: no
  vars:
    vault_addr: "http://localhost:8200"
    vault_token: "myroot"
  
  tasks:
    - name: Fetch AWS credentials from Vault
      uri:
        url: "{{ vault_addr }}/v1/terraform/aws"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        validate_certs: no
      register: vault_aws_secrets
    
    - name: Display AWS credentials
      debug:
        msg: "DB Username: {{ vault_aws_secrets.json.data.data.db_username }}"
    
    - name: Fetch SSH keys from Vault
      uri:
        url: "{{ vault_addr }}/v1/ansible/ssh"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        validate_certs: no
      register: vault_ssh_secrets
    
    - name: Display SSH key info
      debug:
        msg: "SSH keys retrieved successfully"
