- name: Network Services VM Setup
  hosts: all
  become: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

  roles:
    - role: common
    - role: tailscale
    - role: wireguard
    - role: firewall
    - role: adguard
