global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

log:
  level: INFO

accessLog: {}

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
